/* ─────────────────────────────────────────────────────────────────────────────
 * IDIOMAS DO SITE NOVO
 *
 * POR QUE EXISTE: a casca que o Claude Design entregou tem um seletor de idioma
 * DECORATIVO , trocava o selo de EN pra PT e não traduzia nada. O site atual tem
 * 8 idiomas há meses; o novo ia pro ar monolíngue, com 75% do tráfego vindo da
 * Índia e boa parte do Brasil.
 *
 * ⚠️ POR QUE MORA NA RAIZ E NÃO EM novo/: o desempacotador APAGA a pasta novo/
 * inteira a cada entrega do Design. Deixei este arquivo lá na primeira tentativa
 * e ele sumiu no rebuild seguinte , 404 no ar. Mesmo erro que já tinha custado as
 * logos das firmas. Na raiz, o desempacotador não alcança.
 *
 * COMO FUNCIONA: dicionário chaveado pelo texto EM INGLÊS exatamente como aparece
 * na tela. O tradutor roda sobre os NÓS DE TEXTO depois de cada renderização do
 * runtime do Design , sem chave inventada, sem tocar na marcação.
 *
 * ⚠️ NUNCA SE TRADUZ (regra do projeto): nome de firma, cupom, preço, ticker,
 * plataforma, e os termos "Prop Firm", "Profit Split", "Drawdown", "Lifetime".
 * Por isso é ALLOWLIST: o que não está aqui fica em inglês, que é o padrão do site.
 *
 * Traduzido por mim, à mão , nunca por Gemini/API (lei do projeto).
 * ────────────────────────────────────────────────────────────────────────────── */
window.MC_I18N_NOVO = {
  /* ── 3ª rodada (06/08): o que sobrou em inglês na varredura das 15 páginas.
     O site é AMERICANO: o inglês continua sendo o padrão. Isto só entra quando o
     visitante escolhe outro idioma. ⚠️ O subtítulo do hero termina em "from " e o
     PREÇO vive num <span> separado (é outro nó de texto), por isso a chave tem o
     espaço no fim e não inclui o valor , que agora vem do banco. */

  'Exclusive codes for Apex, Bulenox, FTMO, FundedNext and more. A 100K account from': { pt:'Códigos exclusivos de Apex, Bulenox, FTMO, FundedNext e mais. Uma conta de 100K a partir de', es:'Códigos exclusivos de Apex, Bulenox, FTMO, FundedNext y más. Una cuenta de 100K desde', it:'Codici esclusivi di Apex, Bulenox, FTMO, FundedNext e altri. Un account da 100K a partire da', fr:'Codes exclusifs Apex, Bulenox, FTMO, FundedNext et plus. Un compte 100K à partir de', de:'Exklusive Codes für Apex, Bulenox, FTMO, FundedNext und mehr. Ein 100K-Konto ab', ar:'أكواد حصرية لـ Apex و Bulenox و FTMO و FundedNext وغيرها. حساب 100K ابتداءً من', id:'Kode eksklusif untuk Apex, Bulenox, FTMO, FundedNext dan lainnya. Akun 100K mulai dari' },
  'See the whole market at a glance with the integrated heatmap. S&P 500, Nasdaq, Global and Crypto, all in real time.': { pt:'Veja o mercado inteiro de relance com o heatmap integrado. S&P 500, Nasdaq, Global e Cripto, tudo em tempo real.', es:'Mira todo el mercado de un vistazo con el heatmap integrado. S&P 500, Nasdaq, Global y Cripto, todo en tiempo real.', it:'Vedi tutto il mercato a colpo d’occhio con la heatmap integrata. S&P 500, Nasdaq, Global e Cripto, in tempo reale.', fr:'Voyez tout le marché d’un coup d’œil avec la heatmap intégrée. S&P 500, Nasdaq, Global et Crypto, en temps réel.', de:'Sieh den ganzen Markt auf einen Blick mit der integrierten Heatmap. S&P 500, Nasdaq, Global und Krypto, in Echtzeit.', ar:'شاهد السوق كاملًا بنظرة واحدة عبر خريطة الحرارة المدمجة. S&P 500 وناسداك والعالمي والعملات الرقمية، في الوقت الفعلي.', id:'Lihat seluruh pasar sekilas dengan heatmap terintegrasi. S&P 500, Nasdaq, Global dan Kripto, semua real time.' },
  'Real TradingView heatmap with live data': { pt:'Heatmap real do TradingView com dado ao vivo', es:'Heatmap real de TradingView con datos en vivo', it:'Heatmap reale di TradingView con dati live', fr:'Vraie heatmap TradingView en données live', de:'Echte TradingView-Heatmap mit Live-Daten', ar:'خريطة حرارة حقيقية من TradingView ببيانات مباشرة', id:'Heatmap TradingView asli dengan data langsung' },
  'Live TradingView chart embedded for each asset': { pt:'Gráfico do TradingView ao vivo em cada ativo', es:'Gráfico de TradingView en vivo en cada activo', it:'Grafico TradingView live per ogni asset', fr:'Graphique TradingView en direct pour chaque actif', de:'Live-TradingView-Chart für jeden Wert', ar:'رسم TradingView مباشر لكل أصل', id:'Grafik TradingView langsung untuk tiap aset' },
  'Real Trustpilot scores and reviews for each firm': { pt:'Nota e avaliações reais do Trustpilot de cada firma', es:'Puntuación y reseñas reales de Trustpilot de cada firma', it:'Punteggio e recensioni reali di Trustpilot per ogni società', fr:'Note et avis Trustpilot réels pour chaque société', de:'Echte Trustpilot-Bewertungen für jede Firma', ar:'تقييمات Trustpilot حقيقية لكل شركة', id:'Skor dan ulasan Trustpilot asli tiap perusahaan' },

  /* ── 2ª rodada: o que o pente fino de 05/08 achou ainda em inglês ─────────
     ⚠️ NÃO entram aqui de propósito: título de artigo do blog e de guia (são
     CONTEÚDO do banco e já têm versão traduzida própria em /pt/blog e /pt/guides,
     traduzir na interface criaria uma segunda verdade) e nome oficial de evento
     econômico (ISM Services PMI, GDP...), que não se traduz em lugar nenhum. */

  "New coupon or a bigger discount? You get notified the moment it happens. It's free, and you can leave anytime.": { pt:'Cupom novo ou desconto maior? Você é avisado na hora. É grátis e você sai quando quiser.', es:'¿Cupón nuevo o mayor descuento? Te avisamos al instante. Es gratis y puedes salir cuando quieras.', it:'Nuovo coupon o sconto maggiore? Ti avvisiamo subito. È gratis e puoi uscire quando vuoi.', fr:'Nouveau coupon ou remise plus forte ? Vous êtes prévenu aussitôt. C’est gratuit et vous partez quand vous voulez.', de:'Neuer Coupon oder höherer Rabatt? Du wirst sofort benachrichtigt. Kostenlos, jederzeit kündbar.', ar:'كوبون جديد أو خصم أكبر؟ نُعلمك فورًا. مجاني ويمكنك الإلغاء متى شئت.', id:'Kupon baru atau diskon lebih besar? Anda diberi tahu saat itu juga. Gratis dan bisa berhenti kapan saja.' },
  'New coupons first, know before everyone': { pt:'Cupons novos primeiro, saiba antes de todo mundo', es:'Cupones nuevos primero, entérate antes que nadie', it:'Coupon nuovi per primi, prima di tutti', fr:'Les nouveaux coupons d’abord, avant tout le monde', de:'Neue Coupons zuerst, vor allen anderen', ar:'الكوبونات الجديدة أولًا، قبل الجميع', id:'Kupon baru lebih dulu, tahu sebelum yang lain' },
  "Bigger discounts, pinged when a firm's offer rises": { pt:'Descontos maiores, avisado quando a oferta de uma firma sobe', es:'Mayores descuentos, aviso cuando sube la oferta de una firma', it:'Sconti maggiori, avviso quando l’offerta di una società sale', fr:'Remises plus fortes, alerte quand l’offre d’une société augmente', de:'Größere Rabatte, Hinweis wenn ein Angebot steigt', ar:'خصومات أكبر، تنبيه عند ارتفاع عرض أي شركة', id:'Diskon lebih besar, diberi tahu saat penawaran naik' },
  'Last-hours deals, catch offers before they expire': { pt:'Ofertas de última hora, pegue antes de expirar', es:'Ofertas de última hora, aprovecha antes de que expiren', it:'Offerte dell’ultima ora, prendile prima che scadano', fr:'Offres de dernière heure, attrapez-les avant expiration', de:'Last-Minute-Angebote, bevor sie ablaufen', ar:'عروض الساعات الأخيرة، اغتنمها قبل انتهائها', id:'Penawaran jam terakhir, ambil sebelum kedaluwarsa' },
  'Global events that move the markets': { pt:'Eventos globais que movem os mercados', es:'Eventos globales que mueven los mercados', it:'Eventi globali che muovono i mercati', fr:'Les événements mondiaux qui font bouger les marchés', de:'Globale Ereignisse, die die Märkte bewegen', ar:'أحداث عالمية تحرّك الأسواق', id:'Peristiwa global yang menggerakkan pasar' },
  'Pro market analysis every day at 6am': { pt:'Análise de mercado profissional todo dia às 6h', es:'Análisis de mercado profesional cada día a las 6am', it:'Analisi di mercato professionale ogni giorno alle 6', fr:'Analyse de marché pro chaque jour à 6h', de:'Profi-Marktanalyse jeden Tag um 6 Uhr', ar:'تحليل سوق احترافي كل يوم الساعة 6 صباحًا', id:'Analisis pasar profesional setiap hari pukul 6 pagi' },
  'Four assets covered: ES, NQ, Crude and Gold. Bias, supports, resistances, scenarios and macro context with a live chart.': { pt:'Quatro ativos cobertos: ES, NQ, Petróleo e Ouro. Viés, suportes, resistências, cenários e contexto macro com gráfico ao vivo.', es:'Cuatro activos cubiertos: ES, NQ, Petróleo y Oro. Sesgo, soportes, resistencias, escenarios y contexto macro con gráfico en vivo.', it:'Quattro asset coperti: ES, NQ, Petrolio e Oro. Bias, supporti, resistenze, scenari e contesto macro con grafico live.', fr:'Quatre actifs couverts : ES, NQ, Pétrole et Or. Biais, supports, résistances, scénarios et contexte macro avec graphique en direct.', de:'Vier Werte abgedeckt: ES, NQ, Öl und Gold. Bias, Unterstützungen, Widerstände, Szenarien und Makrokontext mit Live-Chart.', ar:'أربعة أصول: ES و NQ والنفط والذهب. الاتجاه والدعوم والمقاومات والسيناريوهات والسياق الكلي مع رسم مباشر.', id:'Empat aset: ES, NQ, Minyak, dan Emas. Bias, support, resistance, skenario, dan konteks makro dengan grafik live.' },
  'has the biggest discount and is our most chosen firm': { pt:'tem o maior desconto e é a firma mais escolhida aqui', es:'tiene el mayor descuento y es la firma más elegida aquí', it:'ha lo sconto maggiore ed è la società più scelta qui', fr:'a la plus grosse remise et c’est la société la plus choisie ici', de:'hat den größten Rabatt und ist unsere meistgewählte Firma', ar:'لديها أكبر خصم وهي الأكثر اختيارًا لدينا', id:'punya diskon terbesar dan paling banyak dipilih di sini' },
  'Put firms side by side and compare drawdown, profit split, prices, platforms and rules. Take the quiz and find the firm that fits you.': { pt:'Coloque as firmas lado a lado e compare drawdown, profit split, preços, plataformas e regras. Faça o quiz e ache a que combina com você.', es:'Pon las firmas lado a lado y compara drawdown, profit split, precios, plataformas y reglas. Haz el quiz y encuentra la que te encaja.', it:'Metti le società a confronto: drawdown, profit split, prezzi, piattaforme e regole. Fai il quiz e trova quella giusta per te.', fr:'Mettez les sociétés côte à côte et comparez drawdown, profit split, prix, plateformes et règles. Faites le quiz et trouvez la vôtre.', de:'Stelle Firmen nebeneinander und vergleiche Drawdown, Profit Split, Preise, Plattformen und Regeln. Mach das Quiz und finde deine.', ar:'ضع الشركات جنبًا إلى جنب وقارن Drawdown و Profit Split والأسعار والمنصات والقواعد. اخض الاختبار واعثر على الأنسب لك.', id:'Sandingkan perusahaan dan bandingkan drawdown, profit split, harga, platform, dan aturan. Ikuti kuis dan temukan yang cocok.' },
  'Access exclusive content and professional indicators, unlocked when you create your free account.': { pt:'Acesse conteúdo exclusivo e indicadores profissionais, liberados ao criar sua conta grátis.', es:'Accede a contenido exclusivo e indicadores profesionales, desbloqueados al crear tu cuenta gratis.', it:'Accedi a contenuti esclusivi e indicatori professionali, sbloccati creando il tuo account gratuito.', fr:'Accédez à du contenu exclusif et des indicateurs pro, débloqués en créant votre compte gratuit.', de:'Exklusive Inhalte und Profi-Indikatoren, freigeschaltet mit deinem kostenlosen Konto.', ar:'محتوى حصري ومؤشرات احترافية تُفتح عند إنشاء حسابك المجاني.', id:'Akses konten eksklusif dan indikator profesional, terbuka saat Anda membuat akun gratis.' },
  'at a discount': { pt:'com desconto', es:'con descuento', it:'in sconto', fr:'à prix réduit', de:'mit Rabatt', ar:'بخصم', id:'dengan diskon' },
  'Get the best trading platforms right on the site. Official licenses at exclusive member prices.': { pt:'Pegue as melhores plataformas direto pelo site. Licenças oficiais a preço exclusivo de membro.', es:'Consigue las mejores plataformas desde el sitio. Licencias oficiales a precio exclusivo de miembro.', it:'Ottieni le migliori piattaforme dal sito. Licenze ufficiali a prezzo esclusivo per i membri.', fr:'Obtenez les meilleures plateformes depuis le site. Licences officielles à prix membre.', de:'Hol dir die besten Plattformen direkt hier. Offizielle Lizenzen zu exklusiven Mitgliederpreisen.', ar:'احصل على أفضل المنصات من الموقع. تراخيص رسمية بأسعار حصرية للأعضاء.', id:'Dapatkan platform terbaik langsung di situs. Lisensi resmi dengan harga khusus anggota.' },
  'Verified marketplace of trading platforms': { pt:'Vitrine verificada de plataformas de trading', es:'Mercado verificado de plataformas de trading', it:'Vetrina verificata di piattaforme di trading', fr:'Place de marché vérifiée de plateformes', de:'Geprüfter Marktplatz für Trading-Plattformen', ar:'سوق موثّق لمنصات التداول', id:'Marketplace platform trading terverifikasi' },
  'Position Size and interactive Quiz': { pt:'Tamanho de posição e Quiz interativo', es:'Tamaño de posición y Quiz interactivo', it:'Dimensione posizione e Quiz interattivo', fr:'Taille de position et Quiz interactif', de:'Positionsgröße und interaktives Quiz', ar:'حجم المركز واختبار تفاعلي', id:'Ukuran Posisi dan Kuis interaktif' },
  'Calculate the ideal size for every trade before you enter. Take the quiz and discover which firm fits your profile and trading style.': { pt:'Calcule o tamanho ideal de cada operação antes de entrar. Faça o quiz e descubra qual firma combina com o seu perfil.', es:'Calcula el tamaño ideal de cada operación antes de entrar. Haz el quiz y descubre qué firma encaja con tu perfil.', it:'Calcola la dimensione ideale di ogni operazione prima di entrare. Fai il quiz e scopri quale società fa per te.', fr:'Calculez la taille idéale de chaque position avant d’entrer. Faites le quiz et découvrez la société qui vous convient.', de:'Berechne die ideale Positionsgröße vor dem Einstieg. Mach das Quiz und finde die passende Firma.', ar:'احسب الحجم المثالي لكل صفقة قبل الدخول. اخض الاختبار واكتشف الشركة المناسبة لك.', id:'Hitung ukuran ideal setiap posisi sebelum masuk. Ikuti kuis dan temukan perusahaan yang cocok.' },
  'Position Size calculator with custom risk': { pt:'Calculadora de tamanho de posição com risco personalizado', es:'Calculadora de tamaño de posición con riesgo personalizado', it:'Calcolatore dimensione posizione con rischio personalizzato', fr:'Calculateur de taille de position avec risque personnalisé', de:'Positionsgrößen-Rechner mit eigenem Risiko', ar:'حاسبة حجم المركز بمخاطرة مخصصة', id:'Kalkulator ukuran posisi dengan risiko kustom' },
  'Smart quiz to find your ideal firm': { pt:'Quiz inteligente pra achar sua firma ideal', es:'Quiz inteligente para encontrar tu firma ideal', it:'Quiz intelligente per trovare la società ideale', fr:'Quiz intelligent pour trouver votre société idéale', de:'Smartes Quiz für deine passende Firma', ar:'اختبار ذكي لإيجاد شركتك المثالية', id:'Kuis cerdas untuk menemukan perusahaan ideal' },
  'Which market do you prefer to trade in?': { pt:'Em qual mercado você prefere operar?', es:'¿En qué mercado prefieres operar?', it:'In quale mercato preferisci operare?', fr:'Sur quel marché préférez-vous trader ?', de:'Auf welchem Markt handelst du am liebsten?', ar:'في أي سوق تفضّل التداول؟', id:'Di pasar mana Anda lebih suka trading?' },
  'Your response will help us find the ideal prop firm.': { pt:'Sua resposta ajuda a achar a Prop Firm ideal.', es:'Tu respuesta nos ayuda a encontrar la Prop Firm ideal.', it:'La tua risposta ci aiuta a trovare la Prop Firm ideale.', fr:'Votre réponse nous aide à trouver la Prop Firm idéale.', de:'Deine Antwort hilft uns, die passende Prop Firm zu finden.', ar:'إجابتك تساعدنا في إيجاد الـ Prop Firm المثالية.', id:'Jawaban Anda membantu kami menemukan Prop Firm ideal.' },
  'Blog, calendar and everything in 8 languages': { pt:'Blog, calendário e tudo em 8 idiomas', es:'Blog, calendario y todo en 8 idiomas', it:'Blog, calendario e tutto in 8 lingue', fr:'Blog, calendrier et tout en 8 langues', de:'Blog, Kalender und alles in 8 Sprachen', ar:'مدونة وتقويم وكل شيء بـ 8 لغات', id:'Blog, kalender, dan semuanya dalam 8 bahasa' },
  'Recognizing the best prop firms based on real data: reviews, discounts, conditions and trader satisfaction.': { pt:'Reconhecendo as melhores Prop Firms com dado real: avaliações, descontos, condições e satisfação do trader.', es:'Reconociendo a las mejores Prop Firms con datos reales: reseñas, descuentos, condiciones y satisfacción del trader.', it:'Riconosciamo le migliori Prop Firm con dati reali: recensioni, sconti, condizioni e soddisfazione del trader.', fr:'Nous distinguons les meilleures Prop Firms sur données réelles : avis, remises, conditions et satisfaction des traders.', de:'Die besten Prop Firms nach echten Daten: Bewertungen, Rabatte, Konditionen und Trader-Zufriedenheit.', ar:'نكرّم أفضل شركات Prop Firm بناءً على بيانات حقيقية: التقييمات والخصومات والشروط ورضا المتداولين.', id:'Mengakui Prop Firm terbaik berdasarkan data nyata: ulasan, diskon, kondisi, dan kepuasan trader.' },
  'Yes. Every code here is free to use. We negotiate them directly with each firm and earn a small affiliate commission when you buy, at no extra cost to you.': { pt:'Sim. Todo código aqui é grátis. A gente negocia direto com cada firma e recebe uma pequena comissão de afiliado quando você compra, sem custo nenhum a mais pra você.', es:'Sí. Todos los códigos son gratis. Los negociamos directamente con cada firma y recibimos una pequeña comisión de afiliado cuando compras, sin coste extra para ti.', it:'Sì. Ogni codice è gratuito. Li negoziamo direttamente con ogni società e riceviamo una piccola commissione di affiliazione quando acquisti, senza costi aggiuntivi per te.', fr:'Oui. Tous les codes sont gratuits. Nous les négocions directement avec chaque société et touchons une petite commission d’affiliation lors de votre achat, sans surcoût pour vous.', de:'Ja. Alle Codes sind kostenlos. Wir verhandeln sie direkt mit jeder Firma und erhalten beim Kauf eine kleine Affiliate-Provision, ohne Mehrkosten für dich.', ar:'نعم. كل الأكواد مجانية. نتفاوض عليها مباشرة مع كل شركة ونحصل على عمولة صغيرة عند الشراء، دون أي تكلفة إضافية عليك.', id:'Ya. Semua kode gratis. Kami menegosiasikannya langsung dengan tiap perusahaan dan menerima komisi afiliasi kecil saat Anda membeli, tanpa biaya tambahan.' },
  'We re-check prices and codes daily against each firm official site. If a code stops working we remove or replace it the same day.': { pt:'A gente confere preços e códigos todo dia no site oficial de cada firma. Se um código para de funcionar, ele sai ou é trocado no mesmo dia.', es:'Revisamos precios y códigos a diario en el sitio oficial de cada firma. Si un código deja de funcionar, lo quitamos o cambiamos el mismo día.', it:'Controlliamo prezzi e codici ogni giorno sul sito ufficiale di ogni società. Se un codice smette di funzionare, lo togliamo o sostituiamo lo stesso giorno.', fr:'Nous vérifions prix et codes chaque jour sur le site officiel de chaque société. Si un code cesse de fonctionner, il est retiré ou remplacé le jour même.', de:'Wir prüfen Preise und Codes täglich auf der offiziellen Seite jeder Firma. Funktioniert ein Code nicht mehr, entfernen oder ersetzen wir ihn am selben Tag.', ar:'نراجع الأسعار والأكواد يوميًا على الموقع الرسمي لكل شركة. وإذا توقف كود عن العمل نزيله أو نستبدله في اليوم نفسه.', id:'Kami memeriksa harga dan kode setiap hari di situs resmi tiap perusahaan. Jika kode berhenti bekerja, kami hapus atau ganti hari itu juga.' },
  'It depends on your market and risk tolerance. Take the 2-minute quiz, it matches your style to futures or forex firms and shows the best active coupon for each.': { pt:'Depende do seu mercado e da sua tolerância a risco. Faça o quiz de 2 minutos: ele cruza o seu perfil com firmas de futuros ou forex e mostra o melhor cupom ativo de cada uma.', es:'Depende de tu mercado y tu tolerancia al riesgo. Haz el quiz de 2 minutos: cruza tu perfil con firmas de futuros o forex y muestra el mejor cupón activo de cada una.', it:'Dipende dal tuo mercato e dalla tua tolleranza al rischio. Fai il quiz di 2 minuti: incrocia il tuo profilo con società futures o forex e mostra il miglior coupon attivo.', fr:'Cela dépend de votre marché et de votre tolérance au risque. Faites le quiz de 2 minutes : il croise votre profil avec les sociétés futures ou forex et affiche le meilleur coupon actif.', de:'Kommt auf deinen Markt und deine Risikobereitschaft an. Mach das 2-Minuten-Quiz: es gleicht dein Profil mit Futures- oder Forex-Firmen ab und zeigt den besten aktiven Coupon.', ar:'يعتمد على سوقك وتحمّلك للمخاطر. اخض اختبار الدقيقتين: يطابق أسلوبك مع شركات العقود الآجلة أو الفوركس ويعرض أفضل كوبون فعّال لكل منها.', id:'Tergantung pasar dan toleransi risiko Anda. Ikuti kuis 2 menit: mencocokkan profil Anda dengan perusahaan futures atau forex dan menampilkan kupon aktif terbaik.' },
  'Verified coupons for the best Prop Firms. Professional tools for futures and forex traders.': { pt:'Cupons verificados das melhores Prop Firms. Ferramentas profissionais para traders de futuros e forex.', es:'Cupones verificados de las mejores Prop Firms. Herramientas profesionales para traders de futuros y forex.', it:'Coupon verificati delle migliori Prop Firm. Strumenti professionali per trader di futures e forex.', fr:'Coupons vérifiés des meilleures Prop Firms. Outils professionnels pour traders futures et forex.', de:'Geprüfte Coupons der besten Prop Firms. Profi-Tools für Futures- und Forex-Trader.', ar:'كوبونات موثقة لأفضل شركات Prop Firm. أدوات احترافية لمتداولي العقود الآجلة والفوركس.', id:'Kupon terverifikasi dari Prop Firm terbaik. Alat profesional untuk trader futures dan forex.' },
  'TRADING PLATFORMS': { pt:'PLATAFORMAS DE TRADING', es:'PLATAFORMAS DE TRADING', it:'PIATTAFORME DI TRADING', fr:'PLATEFORMES DE TRADING', de:'TRADING-PLATTFORMEN', ar:'منصات التداول', id:'PLATFORM TRADING' },
  'The tools used by top prop-firm traders. Compare them and pick the one that fits your style, with exclusive member perks.': { pt:'As ferramentas usadas pelos melhores traders de Prop Firm. Compare e escolha a que combina com você, com vantagens exclusivas de membro.', es:'Las herramientas que usan los mejores traders de Prop Firm. Compara y elige la que encaja contigo, con ventajas exclusivas de miembro.', it:'Gli strumenti usati dai migliori trader di Prop Firm. Confronta e scegli quello adatto a te, con vantaggi esclusivi per i membri.', fr:'Les outils des meilleurs traders de Prop Firm. Comparez et choisissez le vôtre, avec des avantages membres exclusifs.', de:'Die Tools der besten Prop-Firm-Trader. Vergleiche und wähle das passende, mit exklusiven Mitgliedervorteilen.', ar:'الأدوات التي يستخدمها أفضل متداولي Prop Firm. قارن واختر ما يناسبك، مع مزايا حصرية للأعضاء.', id:'Alat yang dipakai trader Prop Firm terbaik. Bandingkan dan pilih yang cocok, dengan keuntungan khusus anggota.' },
  'Real-time alerts': { pt:'Alertas em tempo real', es:'Alertas en tiempo real', it:'Avvisi in tempo reale', fr:'Alertes en temps réel', de:'Echtzeit-Alarme', ar:'تنبيهات فورية', id:'Peringatan waktu nyata' },
  'Multi-market data': { pt:'Dados de vários mercados', es:'Datos de varios mercados', it:'Dati multi-mercato', fr:'Données multi-marchés', de:'Multi-Markt-Daten', ar:'بيانات أسواق متعددة', id:'Data multi-pasar' },
  'FREE AVAILABLE': { pt:'TEM VERSÃO GRÁTIS', es:'HAY VERSIÓN GRATIS', it:'DISPONIBILE GRATIS', fr:'VERSION GRATUITE', de:'KOSTENLOS VERFÜGBAR', ar:'متاح مجانًا', id:'TERSEDIA GRATIS' },
  'Trading Platform': { pt:'Plataforma de trading', es:'Plataforma de trading', it:'Piattaforma di trading', fr:'Plateforme de trading', de:'Trading-Plattform', ar:'منصة تداول', id:'Platform trading' },
  'Free for EOD data': { pt:'Grátis para dados EOD', es:'Gratis para datos EOD', it:'Gratis per dati EOD', fr:'Gratuit pour les données EOD', de:'Kostenlos für EOD-Daten', ar:'مجاني لبيانات نهاية اليوم', id:'Gratis untuk data EOD' },
  'for your desk': { pt:'para a sua mesa', es:'para tu mesa', it:'per la tua postazione', fr:'pour votre desk', de:'für deinen Desk', ar:'لمكتبك', id:'untuk meja Anda' },
  'Filter candles by volume and spot institutional blocks in real time. Plug and play on any chart.': { pt:'Filtre candles por volume e enxergue blocos institucionais em tempo real. Instala e usa, em qualquer gráfico.', es:'Filtra velas por volumen y detecta bloques institucionales en tiempo real. Instala y usa, en cualquier gráfico.', it:'Filtra le candele per volume e individua i blocchi istituzionali in tempo reale. Installa e usa, su qualsiasi grafico.', fr:'Filtrez les bougies par volume et repérez les blocs institutionnels en temps réel. Installez et utilisez, sur tout graphique.', de:'Filtere Kerzen nach Volumen und erkenne institutionelle Blöcke in Echtzeit. Installieren und loslegen, auf jedem Chart.', ar:'رشّح الشموع حسب الحجم واكتشف الكتل المؤسسية لحظيًا. ثبّت واستخدم على أي رسم بياني.', id:'Filter candle berdasarkan volume dan lihat blok institusional secara real time. Pasang dan pakai di grafik mana pun.' },
  'Highlights candles with above-average volume': { pt:'Destaca candles com volume acima da média', es:'Resalta velas con volumen por encima de la media', it:'Evidenzia le candele con volume sopra la media', fr:'Met en évidence les bougies au volume supérieur à la moyenne', de:'Hebt Kerzen mit überdurchschnittlichem Volumen hervor', ar:'يبرز الشموع ذات الحجم فوق المتوسط', id:'Menyorot candle dengan volume di atas rata-rata' },
  'Download free': { pt:'Baixar grátis', es:'Descargar gratis', it:'Scarica gratis', fr:'Télécharger gratuitement', de:'Kostenlos herunterladen', ar:'تحميل مجاني', id:'Unduh gratis' },
  'View details': { pt:'Ver detalhes', es:'Ver detalles', it:'Vedi dettagli', fr:'Voir les détails', de:'Details ansehen', ar:'عرض التفاصيل', id:'Lihat detail' },
  'More indicators coming': { pt:'Mais indicadores a caminho', es:'Más indicadores en camino', it:'Altri indicatori in arrivo', fr:'D’autres indicateurs arrivent', de:'Weitere Indikatoren folgen', ar:'مؤشرات أخرى قادمة', id:'Indikator lain segera hadir' },
  "We're building a full suite of exclusive professional indicators. Create your free account to get access first.": { pt:'Estamos montando um conjunto completo de indicadores profissionais exclusivos. Crie sua conta grátis pra ter acesso primeiro.', es:'Estamos creando un conjunto completo de indicadores profesionales exclusivos. Crea tu cuenta gratis para acceder primero.', it:'Stiamo costruendo una suite completa di indicatori professionali esclusivi. Crea il tuo account gratuito per accedere per primo.', fr:'Nous construisons une suite complète d’indicateurs pro exclusifs. Créez votre compte gratuit pour y accéder en premier.', de:'Wir bauen eine komplette Suite exklusiver Profi-Indikatoren. Erstelle dein kostenloses Konto für den frühen Zugang.', ar:'نبني حزمة كاملة من المؤشرات الاحترافية الحصرية. أنشئ حسابك المجاني لتحصل على الوصول أولًا.', id:'Kami sedang membangun rangkaian lengkap indikator profesional eksklusif. Buat akun gratis untuk akses lebih dulu.' },
  'Create your free account': { pt:'Criar sua conta grátis', es:'Crea tu cuenta gratis', it:'Crea il tuo account gratuito', fr:'Créez votre compte gratuit', de:'Kostenloses Konto erstellen', ar:'أنشئ حسابك المجاني', id:'Buat akun gratis Anda' },
  'Pick up to 3 firms and see discount, price, split, drawdown and rules side by side.': { pt:'Escolha até 3 firmas e veja desconto, preço, split, drawdown e regras lado a lado.', es:'Elige hasta 3 firmas y ve descuento, precio, split, drawdown y reglas lado a lado.', it:'Scegli fino a 3 società e confronta sconto, prezzo, split, drawdown e regole.', fr:'Choisissez jusqu’à 3 sociétés et comparez remise, prix, split, drawdown et règles.', de:'Wähle bis zu 3 Firmen und sieh Rabatt, Preis, Split, Drawdown und Regeln nebeneinander.', ar:'اختر حتى 3 شركات وقارن الخصم والسعر والـ Split والـ Drawdown والقواعد جنبًا إلى جنب.', id:'Pilih hingga 3 perusahaan dan lihat diskon, harga, split, drawdown, dan aturan berdampingan.' },
  'Select at least one firm to start comparing.': { pt:'Escolha pelo menos uma firma pra começar a comparar.', es:'Selecciona al menos una firma para empezar a comparar.', it:'Seleziona almeno una società per iniziare il confronto.', fr:'Sélectionnez au moins une société pour commencer la comparaison.', de:'Wähle mindestens eine Firma, um zu vergleichen.', ar:'اختر شركة واحدة على الأقل لبدء المقارنة.', id:'Pilih setidaknya satu perusahaan untuk mulai membandingkan.' },
  'Daily Market Analysis': { pt:'Análise diária de mercado', es:'Análisis diario de mercado', it:'Analisi giornaliera di mercato', fr:'Analyse quotidienne de marché', de:'Tägliche Marktanalyse', ar:'التحليل اليومي للسوق', id:'Analisis Pasar Harian' },
  'Updated every weekday at 5:00 AM ET. Directional bias, attention zones, news impact, and macro context for the main futures.': { pt:'Atualizada todo dia útil às 5:00 AM ET. Viés direcional, zonas de atenção, impacto das notícias e contexto macro dos principais futuros.', es:'Actualizada cada día hábil a las 5:00 AM ET. Sesgo direccional, zonas de atención, impacto de noticias y contexto macro de los principales futuros.', it:'Aggiornata ogni giorno feriale alle 5:00 AM ET. Bias direzionale, zone di attenzione, impatto delle notizie e contesto macro dei principali futures.', fr:'Mise à jour chaque jour ouvré à 5h00 ET. Biais directionnel, zones d’attention, impact des news et contexte macro des principaux futures.', de:'Jeden Werktag um 5:00 Uhr ET aktualisiert. Richtungsbias, Aufmerksamkeitszonen, Nachrichtenwirkung und Makrokontext der wichtigsten Futures.', ar:'تُحدَّث كل يوم عمل الساعة 5:00 صباحًا ET. الاتجاه ومناطق الانتباه وتأثير الأخبار والسياق الكلي لأهم العقود الآجلة.', id:'Diperbarui setiap hari kerja pukul 5:00 AM ET. Bias arah, zona perhatian, dampak berita, dan konteks makro futures utama.' },
  'Create your free account to continue.': { pt:'Crie sua conta grátis pra continuar.', es:'Crea tu cuenta gratis para continuar.', it:'Crea il tuo account gratuito per continuare.', fr:'Créez votre compte gratuit pour continuer.', de:'Erstelle dein kostenloses Konto, um fortzufahren.', ar:'أنشئ حسابك المجاني للمتابعة.', id:'Buat akun gratis untuk melanjutkan.' },
  'Sign up to get access.': { pt:'Crie conta pra ter acesso.', es:'Regístrate para obtener acceso.', it:'Registrati per ottenere l’accesso.', fr:'Inscrivez-vous pour y accéder.', de:'Registriere dich für den Zugang.', ar:'سجّل للحصول على الوصول.', id:'Daftar untuk mendapat akses.' },
  'Track market maker Gamma Exposure levels across major indices and stocks. See where the largest options concentrations are and how they affect price movement.': { pt:'Acompanhe os níveis de Gamma Exposure dos market makers nos principais índices e ações. Veja onde estão as maiores concentrações de opções e como elas afetam o preço.', es:'Sigue los niveles de Gamma Exposure de los market makers en los principales índices y acciones. Mira dónde están las mayores concentraciones de opciones y cómo afectan al precio.', it:'Segui i livelli di Gamma Exposure dei market maker sui principali indici e titoli. Vedi dove sono le maggiori concentrazioni di opzioni e come influenzano il prezzo.', fr:'Suivez les niveaux de Gamma Exposure des teneurs de marché sur les principaux indices et actions. Voyez où se situent les plus fortes concentrations d’options et leur effet sur le prix.', de:'Verfolge die Gamma-Exposure-Level der Market Maker bei wichtigen Indizes und Aktien. Sieh, wo die größten Optionskonzentrationen liegen und wie sie den Preis beeinflussen.', ar:'تابع مستويات Gamma Exposure لصنّاع السوق على أهم المؤشرات والأسهم. اعرف أين أكبر تركّزات الخيارات وكيف تؤثر على السعر.', id:'Pantau level Gamma Exposure market maker pada indeks dan saham utama. Lihat di mana konsentrasi opsi terbesar dan pengaruhnya pada harga.' },
  'Market cap': { pt:'Valor de mercado', es:'Capitalización', it:'Capitalizzazione', fr:'Capitalisation', de:'Marktkapitalisierung', ar:'القيمة السوقية', id:'Kapitalisasi pasar' },
  'All CCY': { pt:'Todas as moedas', es:'Todas las monedas', it:'Tutte le valute', fr:'Toutes les devises', de:'Alle Währungen', ar:'كل العملات', id:'Semua mata uang' },
  'Calculate the optimal size of your position. Exclusive tool for registered members.': { pt:'Calcule o tamanho ideal da sua posição. Ferramenta exclusiva para membros cadastrados.', es:'Calcula el tamaño óptimo de tu posición. Herramienta exclusiva para miembros registrados.', it:'Calcola la dimensione ottimale della tua posizione. Strumento esclusivo per i membri registrati.', fr:'Calculez la taille optimale de votre position. Outil exclusif aux membres inscrits.', de:'Berechne die optimale Positionsgröße. Exklusives Tool für registrierte Mitglieder.', ar:'احسب الحجم الأمثل لمركزك. أداة حصرية للأعضاء المسجّلين.', id:'Hitung ukuran optimal posisi Anda. Alat eksklusif untuk anggota terdaftar.' },
  'Your information is private. No credit card required.': { pt:'Seus dados são privados. Não pedimos cartão.', es:'Tus datos son privados. No pedimos tarjeta.', it:'I tuoi dati sono privati. Nessuna carta richiesta.', fr:'Vos données restent privées. Aucune carte requise.', de:'Deine Daten bleiben privat. Keine Kreditkarte nötig.', ar:'بياناتك خاصة. لا حاجة لبطاقة ائتمان.', id:'Data Anda bersifat pribadi. Tidak perlu kartu kredit.' },
  'Reviews taken into account': { pt:'Avaliações consideradas', es:'Reseñas consideradas', it:'Recensioni considerate', fr:'Avis pris en compte', de:'Berücksichtigte Bewertungen', ar:'المراجعات المأخوذة بالاعتبار', id:'Ulasan yang diperhitungkan' },
  'Best Profit Split': { pt:'Melhor Profit Split', es:'Mejor Profit Split', it:'Miglior Profit Split', fr:'Meilleur Profit Split', de:'Bester Profit Split', ar:'أفضل Profit Split', id:'Profit Split terbaik' },
  'MORE SPLIT': { pt:'MAIS SPLIT', es:'MÁS SPLIT', it:'PIÙ SPLIT', fr:'PLUS DE SPLIT', de:'MEHR SPLIT', ar:'سبليت أعلى', id:'SPLIT LEBIH' },
  'Best Overall Rating': { pt:'Melhor nota geral', es:'Mejor valoración general', it:'Miglior voto complessivo', fr:'Meilleure note globale', de:'Beste Gesamtbewertung', ar:'أفضل تقييم عام', id:'Rating keseluruhan terbaik' },
  'MORE RELIABLE': { pt:'MAIS CONFIÁVEL', es:'MÁS FIABLE', it:'PIÙ AFFIDABILE', fr:'PLUS FIABLE', de:'ZUVERLÄSSIGER', ar:'الأكثر موثوقية', id:'LEBIH TEPERCAYA' },
  'All firms, ranked by rating': { pt:'Todas as firmas, por nota', es:'Todas las firmas, por valoración', it:'Tutte le società, per voto', fr:'Toutes les sociétés, par note', de:'Alle Firmen nach Bewertung', ar:'كل الشركات مرتّبة حسب التقييم', id:'Semua perusahaan, berdasarkan rating' },
  'Link Discount': { pt:'Desconto pelo link', es:'Descuento por enlace', it:'Sconto tramite link', fr:'Remise par lien', de:'Rabatt über Link', ar:'خصم عبر الرابط', id:'Diskon lewat tautan' },
  'Session starting now': { pt:'Sessão começando agora', es:'Sesión empezando ahora', it:'Sessione in avvio', fr:'Session qui démarre', de:'Session startet jetzt', ar:'الجلسة تبدأ الآن', id:'Sesi dimulai sekarang' },
  'Sharing the screen': { pt:'Compartilhando a tela', es:'Compartiendo la pantalla', it:'Condivisione schermo', fr:'Partage d’écran', de:'Bildschirm wird geteilt', ar:'مشاركة الشاشة', id:'Membagikan layar' },
  'Thanks for the breakdown': { pt:'Valeu pela explicação', es:'Gracias por la explicación', it:'Grazie per la spiegazione', fr:'Merci pour l’explication', de:'Danke für die Erklärung', ar:'شكرًا على الشرح', id:'Terima kasih atas penjelasannya' },
  'honest and complete.': { pt:'honestos e completos.', es:'honestas y completas.', it:'oneste e complete.', fr:'honnêtes et complets.', de:'ehrlich und vollständig.', ar:'صادقة وكاملة.', id:'jujur dan lengkap.' },
  'What is a prop firm?': { pt:'O que é uma Prop Firm?', es:'¿Qué es una Prop Firm?', it:'Cos’è una Prop Firm?', fr:'Qu’est-ce qu’une Prop Firm ?', de:'Was ist eine Prop Firm?', ar:'ما هي الـ Prop Firm؟', id:'Apa itu Prop Firm?' },
  'How to Pass the Challenge': { pt:'Como passar no desafio', es:'Cómo pasar el desafío', it:'Come superare la sfida', fr:'Comment réussir le challenge', de:'Wie du die Challenge bestehst', ar:'كيف تجتاز التحدي', id:'Cara lolos challenge' },
  'How to Withdraw Your Winnings': { pt:'Como sacar seus ganhos', es:'Cómo retirar tus ganancias', it:'Come prelevare i guadagni', fr:'Comment retirer vos gains', de:'Wie du deine Gewinne auszahlst', ar:'كيف تسحب أرباحك', id:'Cara menarik keuntungan Anda' },

  /* navegação e cabeçalho */
  'Log in':            { pt:'Entrar', es:'Iniciar sesión', it:'Accedi', fr:'Connexion', de:'Anmelden', ar:'تسجيل الدخول', id:'Masuk' },
  'Sign up':           { pt:'Criar conta', es:'Registrarse', it:'Registrati', fr:'S’inscrire', de:'Registrieren', ar:'إنشاء حساب', id:'Daftar' },
  'Specials':          { pt:'Ofertas', es:'Ofertas', it:'Offerte', fr:'Offres', de:'Angebote', ar:'العروض', id:'Penawaran' },
  'Firms':             { pt:'Firmas', es:'Firmas', it:'Società', fr:'Sociétés', de:'Firmen', ar:'الشركات', id:'Perusahaan' },
  'Platforms':         { pt:'Plataformas', es:'Plataformas', it:'Piattaforme', fr:'Plateformes', de:'Plattformen', ar:'المنصات', id:'Platform' },
  'Indicators':        { pt:'Indicadores', es:'Indicadores', it:'Indicatori', fr:'Indicateurs', de:'Indikatoren', ar:'المؤشرات', id:'Indikator' },
  'Compare':           { pt:'Comparar', es:'Comparar', it:'Confronta', fr:'Comparer', de:'Vergleichen', ar:'قارن', id:'Bandingkan' },
  'Economic Calendar': { pt:'Calendário econômico', es:'Calendario económico', it:'Calendario economico', fr:'Calendrier économique', de:'Wirtschaftskalender', ar:'التقويم الاقتصادي', id:'Kalender Ekonomi' },
  'Heat Map':          { pt:'Mapa de calor', es:'Mapa de calor', it:'Mappa di calore', fr:'Carte thermique', de:'Heatmap', ar:'خريطة حرارية', id:'Peta Panas' },
  'Daily Analysis':    { pt:'Análise diária', es:'Análisis diario', it:'Analisi giornaliera', fr:'Analyse quotidienne', de:'Tagesanalyse', ar:'التحليل اليومي', id:'Analisis Harian' },
  'Guides':            { pt:'Guias', es:'Guías', it:'Guide', fr:'Guides', de:'Ratgeber', ar:'الأدلة', id:'Panduan' },
  'Position Size':     { pt:'Tamanho de posição', es:'Tamaño de posición', it:'Dimensione posizione', fr:'Taille de position', de:'Positionsgröße', ar:'حجم المركز', id:'Ukuran Posisi' },
  'Quiz':              { pt:'Quiz', es:'Quiz', it:'Quiz', fr:'Quiz', de:'Quiz', ar:'اختبار', id:'Kuis' },
  'Awards':            { pt:'Prêmios', es:'Premios', it:'Premi', fr:'Prix', de:'Auszeichnungen', ar:'الجوائز', id:'Penghargaan' },
  'Live Room':         { pt:'Sala ao vivo', es:'Sala en vivo', it:'Sala live', fr:'Salle live', de:'Live-Raum', ar:'الغرفة المباشرة', id:'Ruang Live' },

  /* hero */
  'VERIFIED · UPDATED DAILY': { pt:'VERIFICADO · ATUALIZADO TODO DIA', es:'VERIFICADO · ACTUALIZADO A DIARIO', it:'VERIFICATO · AGGIORNATO OGNI GIORNO', fr:'VÉRIFIÉ · MIS À JOUR CHAQUE JOUR', de:'GEPRÜFT · TÄGLICH AKTUALISIERT', ar:'مُتحقق · يُحدَّث يوميًا', id:'TERVERIFIKASI · DIPERBARUI HARIAN' },
  /* ── H1 DA HOME (06/08, escrito com a skill do Everton) ──────────────────
     O anterior era "Hunt the [biggest] trading deals" e vinha CORTADO EM 3 NOS
     de texto (o destaque limao fica num <span>), entao a traducao saia palavra
     por palavra: em PT dava "Cace as maiores ofertas de trading". Frankenstein.
     O corte novo foi escolhido pra sobreviver aos 8 idiomas: prefixo + numero +
     resto da frase, e o numero nao se traduz. Mesma promessa da LP /coupons, o
     que mantem as duas superficies coerentes pra quem vem do anuncio.
     ⚠️ "prop firm" NAO se traduz em nenhum idioma (lei do projeto). */
  'Compare': { pt:'Compare', es:'Compara', it:'Confronta', fr:'Comparez', de:'Vergleiche', ar:'قارن بين', id:'Bandingkan' },
  'before you buy': { pt:'antes de comprar', es:'antes de comprar', it:'prima di acquistare', fr:'avant d’acheter', de:'bevor du kaufst', ar:'قبل أن تشتري', id:'sebelum membeli' },
  'See the coupons': { pt:'Ver os cupons', es:'Ver los cupones', it:'Vedi i coupon', fr:'Voir les coupons', de:'Coupons ansehen', ar:'شاهد الكوبونات', id:'Lihat kuponnya' },
  'Compare firms':  { pt:'Comparar firmas', es:'Comparar firmas', it:'Confronta società', fr:'Comparer les sociétés', de:'Firmen vergleichen', ar:'قارن الشركات', id:'Bandingkan Perusahaan' },
  'Trading firms':  { pt:'Firmas de trading', es:'Firmas de trading', it:'Società di trading', fr:'Sociétés de trading', de:'Trading-Firmen', ar:'شركات التداول', id:'Perusahaan trading' },
  'Max discount':   { pt:'Desconto máximo', es:'Descuento máximo', it:'Sconto massimo', fr:'Remise maximale', de:'Maximaler Rabatt', ar:'أقصى خصم', id:'Diskon maksimum' },
  'Monthly views':  { pt:'Visitas por mês', es:'Visitas al mes', it:'Visite al mese', fr:'Vues par mois', de:'Aufrufe pro Monat', ar:'مشاهدات شهرية', id:'Kunjungan per bulan' },
  'Codes copied / mo': { pt:'Cupons copiados / mês', es:'Cupones copiados / mes', it:'Coupon copiati / mese', fr:'Codes copiés / mois', de:'Codes kopiert / Monat', ar:'أكواد منسوخة / شهر', id:'Kode disalin / bln' },
  'Languages':      { pt:'Idiomas', es:'Idiomas', it:'Lingue', fr:'Langues', de:'Sprachen', ar:'لغات', id:'Bahasa' },
  'Max off':        { pt:'Desconto máx.', es:'Descuento máx.', it:'Sconto max', fr:'Remise max', de:'Max. Rabatt', ar:'أقصى خصم', id:'Diskon maks' },
  'Copied/mo':      { pt:'Copiados/mês', es:'Copiados/mes', it:'Copiati/mese', fr:'Copiés/mois', de:'Kopiert/Monat', ar:'منسوخ/شهر', id:'Disalin/bln' },

  /* telegram */
  'Get Exclusive Coupons on Telegram': { pt:'Receba cupons exclusivos no Telegram', es:'Recibe cupones exclusivos en Telegram', it:'Ricevi coupon esclusivi su Telegram', fr:'Recevez des coupons exclusifs sur Telegram', de:'Exklusive Coupons auf Telegram', ar:'احصل على كوبونات حصرية على تيليجرام', id:'Dapatkan Kupon Eksklusif di Telegram' },
  "The codes we can't post publicly go here first": { pt:'Os códigos que não podemos publicar chegam lá primeiro', es:'Los códigos que no podemos publicar llegan allí primero', it:'I codici che non possiamo pubblicare arrivano prima lì', fr:'Les codes que nous ne pouvons pas publier arrivent là en premier', de:'Codes, die wir nicht öffentlich posten können, kommen zuerst dorthin', ar:'الأكواد التي لا يمكننا نشرها علنًا تصل هناك أولًا', id:'Kode yang tidak bisa kami posting publik masuk ke sana lebih dulu' },
  'Join free': { pt:'Entrar grátis', es:'Entrar gratis', it:'Entra gratis', fr:'Rejoindre gratuitement', de:'Kostenlos beitreten', ar:'انضم مجانًا', id:'Gabung gratis' },

  /* cards de firma */
  'Best deals right now': { pt:'Melhores ofertas agora', es:'Mejores ofertas ahora', it:'Migliori offerte ora', fr:'Meilleures offres du moment', de:'Beste Angebote jetzt', ar:'أفضل العروض الآن', id:'Penawaran terbaik saat ini' },
  'EXCLUSIVE COUPON': { pt:'CUPOM EXCLUSIVO', es:'CUPÓN EXCLUSIVO', it:'COUPON ESCLUSIVO', fr:'COUPON EXCLUSIF', de:'EXKLUSIVER COUPON', ar:'كوبون حصري', id:'KUPON EKSKLUSIF' },
  'Copy': { pt:'Copiar', es:'Copiar', it:'Copia', fr:'Copier', de:'Kopieren', ar:'نسخ', id:'Salin' },
  'Use the coupon at checkout': { pt:'Use o cupom no checkout', es:'Usa el cupón en el checkout', it:'Usa il coupon al checkout', fr:'Utilisez le coupon au paiement', de:'Coupon an der Kasse verwenden', ar:'استخدم الكوبون عند الدفع', id:'Gunakan kupon saat checkout' },
  'View plans': { pt:'Ver planos', es:'Ver planes', it:'Vedi piani', fr:'Voir les offres', de:'Pläne ansehen', ar:'عرض الخطط', id:'Lihat paket' },
  'Write a review': { pt:'Escrever avaliação', es:'Escribir reseña', it:'Scrivi una recensione', fr:'Écrire un avis', de:'Bewertung schreiben', ar:'اكتب مراجعة', id:'Tulis ulasan' },
  'Futures': { pt:'Futuros', es:'Futuros', it:'Futures', fr:'Futures', de:'Futures', ar:'العقود الآجلة', id:'Futures' },
  'Forex/Futures': { pt:'Forex/Futuros', es:'Forex/Futuros', it:'Forex/Futures', fr:'Forex/Futures', de:'Forex/Futures', ar:'فوركس/آجلة', id:'Forex/Futures' },
  'Static': { pt:'Estático', es:'Estático', it:'Statico', fr:'Statique', de:'Statisch', ar:'ثابت', id:'Statis' },
  'Fixed': { pt:'Fixo', es:'Fijo', it:'Fisso', fr:'Fixe', de:'Fest', ar:'ثابت', id:'Tetap' },
  'Intraday Trailing': { pt:'Trailing intradiário', es:'Trailing intradía', it:'Trailing intraday', fr:'Trailing intraday', de:'Intraday-Trailing', ar:'متحرك خلال اليوم', id:'Trailing intraday' },
  'Balance-based': { pt:'Sobre o saldo', es:'Sobre el saldo', it:'Sul saldo', fr:'Sur le solde', de:'Saldobasiert', ar:'على أساس الرصيد', id:'Berbasis saldo' },

  /* filtros */
  'DISCOUNT': { pt:'DESCONTO', es:'DESCUENTO', it:'SCONTO', fr:'REMISE', de:'RABATT', ar:'الخصم', id:'DISKON' },
  'Less than 50%': { pt:'Menos de 50%', es:'Menos del 50%', it:'Meno del 50%', fr:'Moins de 50%', de:'Weniger als 50%', ar:'أقل من 50%', id:'Kurang dari 50%' },
  'MY FAVORITES': { pt:'MEUS FAVORITOS', es:'MIS FAVORITOS', it:'I MIEI PREFERITI', fr:'MES FAVORIS', de:'MEINE FAVORITEN', ar:'مفضلتي', id:'FAVORIT SAYA' },
  'Only favorites': { pt:'Só favoritos', es:'Solo favoritos', it:'Solo preferiti', fr:'Favoris uniquement', de:'Nur Favoriten', ar:'المفضلة فقط', id:'Hanya favorit' },
  'Clear filters': { pt:'Limpar filtros', es:'Limpiar filtros', it:'Azzera filtri', fr:'Effacer les filtres', de:'Filter zurücksetzen', ar:'مسح عوامل التصفية', id:'Hapus filter' },
  'Showing': { pt:'Mostrando', es:'Mostrando', it:'Mostrando', fr:'Affichage de', de:'Angezeigt', ar:'عرض', id:'Menampilkan' },
  'companies': { pt:'firmas', es:'firmas', it:'società', fr:'sociétés', de:'Firmen', ar:'شركات', id:'perusahaan' },
  'Higher rating': { pt:'Melhor nota', es:'Mejor valoración', it:'Voto più alto', fr:'Meilleure note', de:'Beste Bewertung', ar:'أعلى تقييم', id:'Rating tertinggi' },
  'Free': { pt:'Grátis', es:'Gratis', it:'Gratis', fr:'Gratuit', de:'Kostenlos', ar:'مجاني', id:'Gratis' },

  /* notificações */
  'App & Coupon Alerts': { pt:'App e alertas de cupom', es:'App y alertas de cupón', it:'App e avvisi coupon', fr:'App et alertes coupon', de:'App & Coupon-Alarme', ar:'التطبيق وتنبيهات الكوبونات', id:'Aplikasi & Peringatan Kupon' },
  'Get the best coupons before everyone else': { pt:'Receba os melhores cupons antes de todo mundo', es:'Recibe los mejores cupones antes que nadie', it:'Ricevi i migliori coupon prima di tutti', fr:'Recevez les meilleurs coupons avant tout le monde', de:'Erhalte die besten Coupons vor allen anderen', ar:'احصل على أفضل الكوبونات قبل الجميع', id:'Dapatkan kupon terbaik sebelum yang lain' },
  'Enable notifications': { pt:'Ativar notificações', es:'Activar notificaciones', it:'Attiva le notifiche', fr:'Activer les notifications', de:'Benachrichtigungen aktivieren', ar:'تفعيل الإشعارات', id:'Aktifkan notifikasi' },
  'New code:': { pt:'Novo cupom:', es:'Nuevo cupón:', it:'Nuovo coupon:', fr:'Nouveau code :', de:'Neuer Code:', ar:'كود جديد:', id:'Kode baru:' },
  'now': { pt:'agora', es:'ahora', it:'ora', fr:'maintenant', de:'jetzt', ar:'الآن', id:'sekarang' },

  /* calendário */
  'Next high-impact event': { pt:'Próximo evento de alto impacto', es:'Próximo evento de alto impacto', it:'Prossimo evento ad alto impatto', fr:'Prochain événement à fort impact', de:'Nächstes Ereignis mit hoher Wirkung', ar:'الحدث التالي عالي التأثير', id:'Peristiwa berdampak tinggi berikutnya' },
  'Time': { pt:'Hora', es:'Hora', it:'Ora', fr:'Heure', de:'Zeit', ar:'الوقت', id:'Waktu' },
  'Currency': { pt:'Moeda', es:'Moneda', it:'Valuta', fr:'Devise', de:'Währung', ar:'العملة', id:'Mata uang' },
  'Event': { pt:'Evento', es:'Evento', it:'Evento', fr:'Événement', de:'Ereignis', ar:'الحدث', id:'Peristiwa' },
  'Actual': { pt:'Atual', es:'Actual', it:'Effettivo', fr:'Réel', de:'Aktuell', ar:'الفعلي', id:'Aktual' },
  'Forecast': { pt:'Previsão', es:'Previsión', it:'Previsione', fr:'Prévision', de:'Prognose', ar:'التوقع', id:'Perkiraan' },
  'Impact': { pt:'Impacto', es:'Impacto', it:'Impatto', fr:'Impact', de:'Auswirkung', ar:'التأثير', id:'Dampak' },

  /* heatmap e análise */
  'Heatmap · US stocks': { pt:'Mapa de calor · ações dos EUA', es:'Mapa de calor · acciones de EE.UU.', it:'Mappa di calore · azioni USA', fr:'Carte thermique · actions US', de:'Heatmap · US-Aktien', ar:'خريطة حرارية · أسهم أمريكية', id:'Peta panas · saham AS' },
  'real time': { pt:'tempo real', es:'tiempo real', it:'tempo reale', fr:'temps réel', de:'Echtzeit', ar:'الوقت الفعلي', id:'waktu nyata' },
  'Heatmap and professional indicators': { pt:'Mapa de calor e indicadores profissionais', es:'Mapa de calor e indicadores profesionales', it:'Mappa di calore e indicatori professionali', fr:'Carte thermique et indicateurs professionnels', de:'Heatmap und professionelle Indikatoren', ar:'خريطة حرارية ومؤشرات احترافية', id:'Peta panas dan indikator profesional' },
  'Gamma Exposure (GEX) levels for major indices': { pt:'Níveis de Gamma Exposure (GEX) dos principais índices', es:'Niveles de Gamma Exposure (GEX) de los principales índices', it:'Livelli di Gamma Exposure (GEX) dei principali indici', fr:'Niveaux de Gamma Exposure (GEX) des principaux indices', de:'Gamma-Exposure-Level (GEX) der wichtigsten Indizes', ar:'مستويات Gamma Exposure لأهم المؤشرات', id:'Level Gamma Exposure (GEX) untuk indeks utama' },
  'Support 1': { pt:'Suporte 1', es:'Soporte 1', it:'Supporto 1', fr:'Support 1', de:'Unterstützung 1', ar:'الدعم 1', id:'Support 1' },
  'Support 2': { pt:'Suporte 2', es:'Soporte 2', it:'Supporto 2', fr:'Support 2', de:'Unterstützung 2', ar:'الدعم 2', id:'Support 2' },
  'Resistance 1': { pt:'Resistência 1', es:'Resistencia 1', it:'Resistenza 1', fr:'Résistance 1', de:'Widerstand 1', ar:'المقاومة 1', id:'Resistance 1' },
  'Resistance 2': { pt:'Resistência 2', es:'Resistencia 2', it:'Resistenza 2', fr:'Résistance 2', de:'Widerstand 2', ar:'المقاومة 2', id:'Resistance 2' },
  'NEUTRAL': { pt:'NEUTRO', es:'NEUTRAL', it:'NEUTRALE', fr:'NEUTRE', de:'NEUTRAL', ar:'محايد', id:'NETRAL' },
  'Daily analysis with zones, scenarios and news impact': { pt:'Análise diária com zonas, cenários e impacto das notícias', es:'Análisis diario con zonas, escenarios e impacto de noticias', it:'Analisi giornaliera con zone, scenari e impatto delle notizie', fr:'Analyse quotidienne avec zones, scénarios et impact des news', de:'Tagesanalyse mit Zonen, Szenarien und Nachrichtenwirkung', ar:'تحليل يومي بالمناطق والسيناريوهات وتأثير الأخبار', id:'Analisis harian dengan zona, skenario, dan dampak berita' },
  'Economic calendar with high-impact events': { pt:'Calendário econômico com eventos de alto impacto', es:'Calendario económico con eventos de alto impacto', it:'Calendario economico con eventi ad alto impatto', fr:'Calendrier économique avec événements à fort impact', de:'Wirtschaftskalender mit wichtigen Ereignissen', ar:'تقويم اقتصادي بأحداث عالية التأثير', id:'Kalender ekonomi dengan peristiwa berdampak tinggi' },
  'every weekday at 5:00 AM ET': { pt:'todo dia útil às 5:00 AM ET', es:'cada día hábil a las 5:00 AM ET', it:'ogni giorno feriale alle 5:00 AM ET', fr:'chaque jour ouvré à 5h00 ET', de:'jeden Werktag um 5:00 Uhr ET', ar:'كل يوم عمل الساعة 5:00 صباحًا ET', id:'setiap hari kerja pukul 5:00 AM ET' },
  'professional': { pt:'profissional', es:'profesional', it:'professionale', fr:'professionnelle', de:'professionell', ar:'احترافي', id:'profesional' },

  /* comparar e quiz */
  'Firm': { pt:'Firma', es:'Firma', it:'Società', fr:'Société', de:'Firma', ar:'الشركة', id:'Perusahaan' },
  'Discount': { pt:'Desconto', es:'Descuento', it:'Sconto', fr:'Remise', de:'Rabatt', ar:'الخصم', id:'Diskon' },
  'Funded': { pt:'Financiada', es:'Fondeada', it:'Finanziata', fr:'Financée', de:'Finanziert', ar:'ممولة', id:'Didanai' },
  'Compare & Quiz': { pt:'Comparar e Quiz', es:'Comparar y Quiz', it:'Confronta e Quiz', fr:'Comparer et Quiz', de:'Vergleichen & Quiz', ar:'قارن واختبر', id:'Bandingkan & Kuis' },
  'Compare every firm before you choose': { pt:'Compare todas as firmas antes de escolher', es:'Compara todas las firmas antes de elegir', it:'Confronta tutte le società prima di scegliere', fr:'Comparez toutes les sociétés avant de choisir', de:'Vergleiche alle Firmen, bevor du wählst', ar:'قارن كل الشركات قبل الاختيار', id:'Bandingkan semua perusahaan sebelum memilih' },
  'Visual comparator with filters by type, price and rules': { pt:'Comparador visual com filtros por tipo, preço e regras', es:'Comparador visual con filtros por tipo, precio y reglas', it:'Comparatore visivo con filtri per tipo, prezzo e regole', fr:'Comparateur visuel avec filtres par type, prix et règles', de:'Visueller Vergleich mit Filtern nach Typ, Preis und Regeln', ar:'مقارن مرئي مع فلاتر حسب النوع والسعر والقواعد', id:'Pembanding visual dengan filter tipe, harga, dan aturan' },
  'Interactive quiz, find your ideal firm in 2 minutes': { pt:'Quiz interativo: ache sua firma ideal em 2 minutos', es:'Quiz interactivo: encuentra tu firma ideal en 2 minutos', it:'Quiz interattivo: trova la società ideale in 2 minuti', fr:'Quiz interactif : trouvez votre société idéale en 2 minutes', de:'Interaktives Quiz: finde in 2 Minuten deine passende Firma', ar:'اختبار تفاعلي: اعثر على شركتك المثالية في دقيقتين', id:'Kuis interaktif: temukan perusahaan ideal dalam 2 menit' },
  'Quiz · Your ideal firm': { pt:'Quiz · Sua firma ideal', es:'Quiz · Tu firma ideal', it:'Quiz · La tua società ideale', fr:'Quiz · Votre société idéale', de:'Quiz · Deine passende Firma', ar:'اختبار · شركتك المثالية', id:'Kuis · Perusahaan ideal Anda' },
  'Both': { pt:'Os dois', es:'Ambos', it:'Entrambi', fr:'Les deux', de:'Beide', ar:'كلاهما', id:'Keduanya' },

  /* live room */
  'Live & Indicators': { pt:'Ao vivo e indicadores', es:'En vivo e indicadores', it:'Live e indicatori', fr:'Live et indicateurs', de:'Live & Indikatoren', ar:'مباشر ومؤشرات', id:'Live & Indikator' },
  'VIP Live Room and exclusive indicators': { pt:'Sala VIP ao vivo e indicadores exclusivos', es:'Sala VIP en vivo e indicadores exclusivos', it:'Sala VIP live e indicatori esclusivi', fr:'Salle VIP live et indicateurs exclusifs', de:'VIP-Live-Raum und exklusive Indikatoren', ar:'غرفة VIP مباشرة ومؤشرات حصرية', id:'Ruang VIP live dan indikator eksklusif' },
  'Exclusive sessions for VIP members': { pt:'Sessões exclusivas para membros VIP', es:'Sesiones exclusivas para miembros VIP', it:'Sessioni esclusive per membri VIP', fr:'Sessions exclusives pour les membres VIP', de:'Exklusive Sessions für VIP-Mitglieder', ar:'جلسات حصرية لأعضاء VIP', id:'Sesi eksklusif untuk anggota VIP' },
  'Professional indicators for members only': { pt:'Indicadores profissionais só para membros', es:'Indicadores profesionales solo para miembros', it:'Indicatori professionali solo per membri', fr:'Indicateurs professionnels réservés aux membres', de:'Professionelle Indikatoren nur für Mitglieder', ar:'مؤشرات احترافية للأعضاء فقط', id:'Indikator profesional khusus anggota' },
  'Monthly funded-account giveaways': { pt:'Sorteios mensais de conta financiada', es:'Sorteos mensuales de cuenta fondeada', it:'Giveaway mensili di conto finanziato', fr:'Tirages mensuels de comptes financés', de:'Monatliche Verlosungen finanzierter Konten', ar:'سحوبات شهرية على حسابات ممولة', id:'Undian akun didanai bulanan' },

  /* ferramentas */
  'Free Tools': { pt:'Ferramentas grátis', es:'Herramientas gratis', it:'Strumenti gratuiti', fr:'Outils gratuits', de:'Kostenlose Tools', ar:'أدوات مجانية', id:'Alat gratis' },
  'Position Size Calculator': { pt:'Calculadora de tamanho de posição', es:'Calculadora de tamaño de posición', it:'Calcolatore dimensione posizione', fr:'Calculateur de taille de position', de:'Positionsgrößen-Rechner', ar:'حاسبة حجم المركز', id:'Kalkulator ukuran posisi' },
  'Account': { pt:'Conta', es:'Cuenta', it:'Conto', fr:'Compte', de:'Konto', ar:'الحساب', id:'Akun' },
  'Contracts': { pt:'Contratos', es:'Contratos', it:'Contratti', fr:'Contrats', de:'Kontrakte', ar:'العقود', id:'Kontrak' },
  'Professional risk-management tools': { pt:'Ferramentas profissionais de gestão de risco', es:'Herramientas profesionales de gestión de riesgo', it:'Strumenti professionali di gestione del rischio', fr:'Outils professionnels de gestion du risque', de:'Professionelle Risikomanagement-Tools', ar:'أدوات احترافية لإدارة المخاطر', id:'Alat manajemen risiko profesional' },

  /* guias e blog */
  'Guides & Education': { pt:'Guias e educação', es:'Guías y educación', it:'Guide e formazione', fr:'Guides et formation', de:'Ratgeber & Wissen', ar:'الأدلة والتعليم', id:'Panduan & Edukasi' },
  'BEGINNER': { pt:'INICIANTE', es:'PRINCIPIANTE', it:'PRINCIPIANTE', fr:'DÉBUTANT', de:'ANFÄNGER', ar:'مبتدئ', id:'PEMULA' },
  'INTERMEDIATE': { pt:'INTERMEDIÁRIO', es:'INTERMEDIO', it:'INTERMEDIO', fr:'INTERMÉDIAIRE', de:'FORTGESCHRITTEN', ar:'متوسط', id:'MENENGAH' },
  'PRACTICAL': { pt:'PRÁTICO', es:'PRÁCTICO', it:'PRATICO', fr:'PRATIQUE', de:'PRAXIS', ar:'عملي', id:'PRAKTIS' },

  /* awards */
  'Winner': { pt:'Vencedora', es:'Ganadora', it:'Vincitrice', fr:'Gagnante', de:'Gewinner', ar:'الفائز', id:'Pemenang' },
  'Runner-up': { pt:'Vice', es:'Segunda', it:'Seconda', fr:'Deuxième', de:'Zweiter', ar:'الوصيف', id:'Runner-up' },
  'Third': { pt:'Terceira', es:'Tercera', it:'Terza', fr:'Troisième', de:'Dritter', ar:'الثالث', id:'Ketiga' },
  'Best Overall': { pt:'Melhor geral', es:'Mejor general', it:'Migliore in assoluto', fr:'Meilleure globale', de:'Beste insgesamt', ar:'الأفضل إجمالًا', id:'Terbaik keseluruhan' },
  'Best for Futures': { pt:'Melhor para futuros', es:'Mejor para futuros', it:'Migliore per i futures', fr:'Meilleure pour les futures', de:'Beste für Futures', ar:'الأفضل للعقود الآجلة', id:'Terbaik untuk futures' },
  'Biggest Discount': { pt:'Maior desconto', es:'Mayor descuento', it:'Sconto maggiore', fr:'Plus grosse remise', de:'Größter Rabatt', ar:'أكبر خصم', id:'Diskon terbesar' },
  'Firms analyzed': { pt:'Firmas analisadas', es:'Firmas analizadas', it:'Società analizzate', fr:'Sociétés analysées', de:'Analysierte Firmen', ar:'شركات تم تحليلها', id:'Perusahaan dianalisis' },
  'Reviews considered': { pt:'Avaliações consideradas', es:'Reseñas consideradas', it:'Recensioni considerate', fr:'Avis pris en compte', de:'Berücksichtigte Bewertungen', ar:'مراجعات مأخوذة بالاعتبار', id:'Ulasan dipertimbangkan' },
  'Award categories': { pt:'Categorias premiadas', es:'Categorías premiadas', it:'Categorie premiate', fr:'Catégories primées', de:'Auszeichnungskategorien', ar:'فئات الجوائز', id:'Kategori penghargaan' },

  /* FAQ */
  'Frequently asked questions': { pt:'Perguntas frequentes', es:'Preguntas frecuentes', it:'Domande frequenti', fr:'Questions fréquentes', de:'Häufige Fragen', ar:'الأسئلة الشائعة', id:'Pertanyaan umum' },
  'Are the coupons really free?': { pt:'Os cupons são mesmo grátis?', es:'¿Los cupones son realmente gratis?', it:'I coupon sono davvero gratuiti?', fr:'Les coupons sont-ils vraiment gratuits ?', de:'Sind die Coupons wirklich kostenlos?', ar:'هل الكوبونات مجانية فعلًا؟', id:'Apakah kupon benar-benar gratis?' },
  'How do I use a coupon code?': { pt:'Como uso um cupom?', es:'¿Cómo uso un cupón?', it:'Come uso un coupon?', fr:'Comment utiliser un coupon ?', de:'Wie nutze ich einen Coupon?', ar:'كيف أستخدم الكوبون؟', id:'Bagaimana cara memakai kupon?' },
  'Are the discounts verified and up to date?': { pt:'Os descontos são verificados e atualizados?', es:'¿Los descuentos están verificados y al día?', it:'Gli sconti sono verificati e aggiornati?', fr:'Les remises sont-elles vérifiées et à jour ?', de:'Sind die Rabatte geprüft und aktuell?', ar:'هل الخصومات موثقة ومحدثة؟', id:'Apakah diskon terverifikasi dan terbaru?' },
  'Which firm is best for beginners?': { pt:'Qual firma é melhor para iniciantes?', es:'¿Qué firma es mejor para principiantes?', it:'Quale società è migliore per i principianti?', fr:'Quelle société convient aux débutants ?', de:'Welche Firma eignet sich für Einsteiger?', ar:'أي شركة أفضل للمبتدئين؟', id:'Perusahaan mana yang terbaik untuk pemula?' },
  'Do you offer support if I have a problem?': { pt:'Vocês dão suporte se eu tiver problema?', es:'¿Ofrecen soporte si tengo un problema?', it:'Offrite assistenza in caso di problemi?', fr:'Proposez-vous une assistance en cas de problème ?', de:'Bietet ihr Support bei Problemen?', ar:'هل تقدمون دعمًا إذا واجهت مشكلة؟', id:'Apakah ada dukungan jika saya bermasalah?' },

  /* rodapé */
  'Newsletter': { pt:'Newsletter', es:'Newsletter', it:'Newsletter', fr:'Newsletter', de:'Newsletter', ar:'النشرة البريدية', id:'Newsletter' },
  'Get the best Prop Firm deals and tips every week.': { pt:'Receba as melhores ofertas de Prop Firm e dicas toda semana.', es:'Recibe las mejores ofertas de Prop Firm y consejos cada semana.', it:'Ricevi ogni settimana le migliori offerte Prop Firm e consigli.', fr:'Recevez chaque semaine les meilleures offres Prop Firm et des conseils.', de:'Erhalte wöchentlich die besten Prop-Firm-Angebote und Tipps.', ar:'احصل على أفضل عروض Prop Firm ونصائح كل أسبوع.', id:'Dapatkan penawaran Prop Firm terbaik dan tips setiap minggu.' },
  'Subscribe': { pt:'Inscrever', es:'Suscribirse', it:'Iscriviti', fr:'S’abonner', de:'Abonnieren', ar:'اشترك', id:'Berlangganan' },
  'Trading Firms': { pt:'Firmas de trading', es:'Firmas de trading', it:'Società di trading', fr:'Sociétés de trading', de:'Trading-Firmen', ar:'شركات التداول', id:'Perusahaan trading' },
  'Tools': { pt:'Ferramentas', es:'Herramientas', it:'Strumenti', fr:'Outils', de:'Tools', ar:'الأدوات', id:'Alat' },
  'Company Quiz': { pt:'Quiz de firmas', es:'Quiz de firmas', it:'Quiz società', fr:'Quiz sociétés', de:'Firmen-Quiz', ar:'اختبار الشركات', id:'Kuis perusahaan' },
  'Comparison Tool': { pt:'Comparador', es:'Comparador', it:'Comparatore', fr:'Comparateur', de:'Vergleichstool', ar:'أداة المقارنة', id:'Alat perbandingan' },
  'Calendar': { pt:'Calendário', es:'Calendario', it:'Calendario', fr:'Calendrier', de:'Kalender', ar:'التقويم', id:'Kalender' },
  'App & Alerts': { pt:'App e alertas', es:'App y alertas', it:'App e avvisi', fr:'App et alertes', de:'App & Alarme', ar:'التطبيق والتنبيهات', id:'Aplikasi & Peringatan' },
  'Top Lists': { pt:'Listas', es:'Listas', it:'Classifiche', fr:'Classements', de:'Bestenlisten', ar:'القوائم', id:'Daftar Teratas' },
  'With Exclusive Coupon': { pt:'Com cupom exclusivo', es:'Con cupón exclusivo', it:'Con coupon esclusivo', fr:'Avec coupon exclusif', de:'Mit exklusivem Coupon', ar:'بكوبون حصري', id:'Dengan kupon eksklusif' },
  'No Activation Fee': { pt:'Sem taxa de ativação', es:'Sin cuota de activación', it:'Senza costo di attivazione', fr:'Sans frais d’activation', de:'Ohne Aktivierungsgebühr', ar:'بدون رسوم تفعيل', id:'Tanpa biaya aktivasi' },
  'Cheapest': { pt:'Mais baratas', es:'Más baratas', it:'Più economiche', fr:'Les moins chères', de:'Günstigste', ar:'الأرخص', id:'Termurah' },
  'Highest Rated': { pt:'Melhor avaliadas', es:'Mejor valoradas', it:'Meglio valutate', fr:'Les mieux notées', de:'Bestbewertet', ar:'الأعلى تقييمًا', id:'Rating tertinggi' },
  'Links': { pt:'Links', es:'Enlaces', it:'Link', fr:'Liens', de:'Links', ar:'روابط', id:'Tautan' },
  'Legal': { pt:'Jurídico', es:'Legal', it:'Legale', fr:'Mentions légales', de:'Rechtliches', ar:'قانوني', id:'Legal' },
  'Privacy Policy': { pt:'Política de privacidade', es:'Política de privacidad', it:'Informativa privacy', fr:'Politique de confidentialité', de:'Datenschutz', ar:'سياسة الخصوصية', id:'Kebijakan Privasi' },
  'Terms of Use': { pt:'Termos de uso', es:'Términos de uso', it:'Termini d’uso', fr:'Conditions d’utilisation', de:'Nutzungsbedingungen', ar:'شروط الاستخدام', id:'Ketentuan Penggunaan' },
  'Cookie Policy': { pt:'Política de cookies', es:'Política de cookies', it:'Informativa cookie', fr:'Politique de cookies', de:'Cookie-Richtlinie', ar:'سياسة ملفات الارتباط', id:'Kebijakan Cookie' },
  'Privacy': { pt:'Privacidade', es:'Privacidad', it:'Privacy', fr:'Confidentialité', de:'Datenschutz', ar:'الخصوصية', id:'Privasi' },
  'Terms': { pt:'Termos', es:'Términos', it:'Termini', fr:'Conditions', de:'AGB', ar:'الشروط', id:'Ketentuan' },
  'Home': { pt:'Início', es:'Inicio', it:'Home', fr:'Accueil', de:'Start', ar:'الرئيسية', id:'Beranda' },
  'Verified coupons, updated daily. Trading involves risk.': { pt:'Cupons verificados, atualizados todo dia. Trading envolve risco.', es:'Cupones verificados, actualizados a diario. El trading implica riesgo.', it:'Coupon verificati, aggiornati ogni giorno. Il trading comporta rischi.', fr:'Coupons vérifiés, mis à jour chaque jour. Le trading comporte des risques.', de:'Geprüfte Coupons, täglich aktualisiert. Trading birgt Risiken.', ar:'كوبونات موثقة، تُحدَّث يوميًا. التداول ينطوي على مخاطر.', id:'Kupon terverifikasi, diperbarui harian. Trading mengandung risiko.' },

  /* cadastro e login */
  'Create Account': { pt:'Criar conta', es:'Crear cuenta', it:'Crea account', fr:'Créer un compte', de:'Konto erstellen', ar:'إنشاء حساب', id:'Buat akun' },
  'Create account': { pt:'Criar conta', es:'Crear cuenta', it:'Crea account', fr:'Créer un compte', de:'Konto erstellen', ar:'إنشاء حساب', id:'Buat akun' },
  'Sign In': { pt:'Entrar', es:'Iniciar sesión', it:'Accedi', fr:'Se connecter', de:'Anmelden', ar:'تسجيل الدخول', id:'Masuk' },
  'Welcome to': { pt:'Bem-vindo à', es:'Bienvenido a', it:'Benvenuto in', fr:'Bienvenue chez', de:'Willkommen bei', ar:'مرحبًا بك في', id:'Selamat datang di' },
  'Unlock limitless trading opportunities.': { pt:'Destrave oportunidades ilimitadas de trading.', es:'Desbloquea oportunidades de trading sin límite.', it:'Sblocca opportunità di trading illimitate.', fr:'Débloquez des opportunités de trading illimitées.', de:'Schalte grenzenlose Trading-Chancen frei.', ar:'افتح فرص تداول بلا حدود.', id:'Buka peluang trading tanpa batas.' },
  'Sign up with Google': { pt:'Criar conta com Google', es:'Registrarse con Google', it:'Registrati con Google', fr:'S’inscrire avec Google', de:'Mit Google registrieren', ar:'التسجيل عبر Google', id:'Daftar dengan Google' },
  'or sign up with email': { pt:'ou crie conta com e-mail', es:'o regístrate con email', it:'oppure registrati con email', fr:'ou inscrivez-vous par e-mail', de:'oder mit E-Mail registrieren', ar:'أو سجّل بالبريد الإلكتروني', id:'atau daftar dengan email' },
  'To join promotions and giveaways we need your real data and best email.': { pt:'Para participar de promoções e sorteios precisamos dos seus dados reais e do seu melhor e-mail.', es:'Para participar en promociones y sorteos necesitamos tus datos reales y tu mejor email.', it:'Per partecipare a promozioni e giveaway servono i tuoi dati reali e la tua email migliore.', fr:'Pour participer aux promotions et tirages, nous avons besoin de vos vraies données et de votre meilleure adresse e-mail.', de:'Für Aktionen und Verlosungen brauchen wir deine echten Daten und deine beste E-Mail-Adresse.', ar:'للمشاركة في العروض والسحوبات نحتاج بياناتك الحقيقية وأفضل بريد إلكتروني لديك.', id:'Untuk ikut promosi dan undian, kami perlu data asli dan email terbaik Anda.' },
  'FULL NAME': { pt:'NOME COMPLETO', es:'NOMBRE COMPLETO', it:'NOME COMPLETO', fr:'NOM COMPLET', de:'VOLLSTÄNDIGER NAME', ar:'الاسم الكامل', id:'NAMA LENGKAP' },
  'EMAIL': { pt:'E-MAIL', es:'EMAIL', it:'EMAIL', fr:'E-MAIL', de:'E-MAIL', ar:'البريد الإلكتروني', id:'EMAIL' },
  'PASSWORD (MIN. 6 CHARACTERS)': { pt:'SENHA (MÍN. 6 CARACTERES)', es:'CONTRASEÑA (MÍN. 6 CARACTERES)', it:'PASSWORD (MIN. 6 CARATTERI)', fr:'MOT DE PASSE (MIN. 6 CARACTÈRES)', de:'PASSWORT (MIND. 6 ZEICHEN)', ar:'كلمة المرور (6 أحرف على الأقل)', id:'KATA SANDI (MIN. 6 KARAKTER)' },
  'I have read and accept the': { pt:'Li e aceito a', es:'He leído y acepto la', it:'Ho letto e accetto la', fr:'J’ai lu et j’accepte la', de:'Ich habe gelesen und akzeptiere die', ar:'قرأت وأوافق على', id:'Saya telah membaca dan menerima' },
  'I want to receive exclusive coupons and offers by email (+1 giveaway entry)': { pt:'Quero receber cupons e ofertas exclusivas por e-mail (+1 bilhete no sorteio)', es:'Quiero recibir cupones y ofertas exclusivas por email (+1 boleto en el sorteo)', it:'Voglio ricevere coupon e offerte esclusive via email (+1 biglietto al giveaway)', fr:'Je veux recevoir des coupons et offres exclusives par e-mail (+1 participation au tirage)', de:'Ich möchte exklusive Coupons und Angebote per E-Mail erhalten (+1 Los für die Verlosung)', ar:'أريد تلقي كوبونات وعروض حصرية بالبريد (+1 فرصة في السحب)', id:'Saya ingin menerima kupon dan penawaran eksklusif via email (+1 tiket undian)' },
  'Already have an account?': { pt:'Já tem conta?', es:'¿Ya tienes cuenta?', it:'Hai già un account?', fr:'Vous avez déjà un compte ?', de:'Schon ein Konto?', ar:'لديك حساب بالفعل؟', id:'Sudah punya akun?' }
};
