// Splita i18n.js (~457kb com 7 idiomas) em arquivos por idioma.
// Cada arquivo: i18n/{lang}.js com `window.I18N = window.I18N || {}; window.I18N.{lang} = {...}`
// Mobile boot carrega só o idioma ativo (-390kb upfront).

import fs from 'node:fs';
import path from 'node:path';

const SRC = 'i18n.js';
const OUT_DIR = 'i18n';

const src = fs.readFileSync(SRC, 'utf8');
const langs = ['pt', 'en', 'es', 'it', 'fr', 'de', 'ar'];

fs.mkdirSync(OUT_DIR, { recursive: true });

// Encontra o início do objeto raiz `const I18N = {`
const rootStart = src.indexOf('const I18N = {');
if (rootStart < 0) { console.error('I18N root not found'); process.exit(1); }

// Encontra cada bloco de idioma, usa regex pra início, depois match braces
function extractLangBlock(lang) {
  const re = new RegExp(`^\\s{2}${lang}:\\s*\\{`, 'm');
  const m = re.exec(src);
  if (!m) { console.error(`Bloco ${lang} não encontrado`); return null; }
  const startBrace = src.indexOf('{', m.index);
  let depth = 0, i = startBrace;
  for (; i < src.length; i++) {
    const c = src[i];
    if (c === '{') depth++;
    else if (c === '}') { depth--; if (depth === 0) { i++; break; } }
    else if (c === '"' || c === "'") {
      // Skip string
      const quote = c;
      i++;
      while (i < src.length && src[i] !== quote) {
        if (src[i] === '\\') i++;
        i++;
      }
    }
  }
  // Inclui possível vírgula trailing
  const block = src.slice(startBrace, i);
  return block;
}

let totalSize = 0;
for (const lang of langs) {
  const obj = extractLangBlock(lang);
  if (!obj) continue;
  const out = `// Generated by scripts/_split-i18n.mjs, DO NOT EDIT MANUALLY.
// Source of truth: i18n.js (full file). Re-split with: node scripts/_split-i18n.mjs
window.I18N = window.I18N || {};
window.I18N.${lang} = ${obj};
window.dispatchEvent(new CustomEvent('mc-i18n-loaded', { detail: { lang: '${lang}' } }));
`;
  const outPath = path.join(OUT_DIR, `${lang}.js`);
  fs.writeFileSync(outPath, out, 'utf8');
  const size = (out.length / 1024).toFixed(1);
  totalSize += out.length;
  console.log(`✓ ${outPath} (${size}kb)`);
}

console.log(`\nTotal: ${(totalSize/1024).toFixed(1)}kb (vs i18n.js full ${(src.length/1024).toFixed(1)}kb)`);
console.log(`\nNEXT: substituir <script src="i18n.js"> por loader que carrega só o idioma ativo.`);
